name: frappe_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  signature: ^4.1.1
  flutter_mentions: ^2.0.1
  photo_view: ^0.11.1
  flutter_easyloading: ^3.0.0
  html_editor_enhanced: ^2.1.0+1
  flutter_typeahead: ^3.1.1
  flutter_chips_input: ^1.9.5
  timelines: ^0.1.0
  persistent_bottom_nav_bar: ^4.0.2
  overflow_view: ^0.3.1
  injectable:
  json_table: ^2.0.1
  barcode_widget: ^2.0.1
  shared_preferences: ^2.0.5
  crypto: ^3.0.1
  device_info: ^2.0.0
  flutter_local_notifications: ^5.0.0+1
  # workmanager: ^0.4.0
  get_it: ^6.1.1
  fluttertoast: ^8.0.4
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  connectivity: ^3.0.3
  provider: ^5.0.0
  open_file: ^3.1.0
  flutter_svg: ^0.22.0
  collection: ^1.15.0
  cached_network_image: ^3.0.0
  google_fonts: ^2.0.0
  file_picker: ^3.0.1
  flutter_form_builder: ^6.0.0
  flutter_pagewise: ^2.0.1
  html: ^0.15.0
  url_launcher: ^6.0.3
  permission_handler: ^6.1.3
  flutter_downloader: ^1.6.0
  timeago: ^3.0.2
  path_provider: ^2.0.1
  flutter_html: ^2.0.0
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  intl: ^0.17.0
  flutter_swiper: ^1.1.6
  flutter_barcode_scanner: ^2.0.0
  uuid: ^3.0.4
  charts_flutter: ^0.11.0
  flutter_rating_bar: ^4.0.0
  chips_choice: ^2.0.1
  rflutter_alert: ^2.0.4
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bootstrap: ^2.0.0
  dotted_border: ^2.0.0

dev_dependencies:
  build_runner:
  injectable_generator:
  hive_generator: ^1.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/frappe_icon.jpg"

dependency_overrides:
  flutter_form_builder:
    git:
      url: https://github.com/sumitbhanushali/flutter_form_builder
      ref: e80fdaa31c6150bdb503f1437b9fa9cf127d0380

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
